### PR TITLE
Add option to use GPS location

### PR DESCRIPTION
**Pull request by andarotajo**
Hey, I looked into the matter I asked about and it was actually easier than I anticipated!! I don't know anything about this geography stuff but luckily the WFS API implemented a lot of functions from the GeoServer which do basically all the work.

This would be my idea of the change, basically only extending the existing API with the option to use a GPS location. The query stuff can be kept unchanged because the response from WFS is the same, if the GPS coordinates were valid and in a region that's covered. I'm not that experienced with Python so feel free to improve the code :) 

Getting this into the library and up on pypi would be awesome! My next project would be trying to extend the official Home Assistant integration that's using this library, that will be tough :D

### CODE REVIEW

**Comment by stephan192** [comment]
You're right, easier than expected.
Thank you.

**Comment by stephan192** [comment]
I've released v1.0.6 to PyPI.

I wish you good success with your further coding.
I for myself currently stopped all my effords bringing the weather warnings integration any step further due to the fact that my last pull request was rejected due to architectural issues.
https://github.com/home-assistant/core/pull/67068
https://github.com/home-assistant/core/issues/66694

I currently don't have enough spare time to switch the integration to config flow and the documentation of config flow is, in my option, far away from complete.

**Comment by andarotajo** [comment]
Thanks!

So config flow is required now, didn't know that yet :D I've considered trying to switch it to config flow but now I don't have much choice :D If it doesn't work out, I can still use it as a custom integration, we'll see

**Comment by andarotajo** [comment]
Now that I think about it, maybe I should've extended the `update` method with the option to provide a new GPS location. Now I'd have to create a new object for every update cycle, if I want it to update the warncell ID based on my location.

I might create another pull request :/

**Pull request merged**
